# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'load.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(823, 722)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 10, 801, 701))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 20, 341, 671))
        self.label.setStyleSheet("background-image: url(:/newPrefix/glass.jpg);\n"
"border-top-left-radius: 50px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(390, 160, 351, 51))
        self.comboBox.setStyleSheet("QComboBox#comboBox{\n"
"    background-color:rgba(0, 0, 0, 0);\n"
"    font: 14pt \"Segoe UI\";\n"
"    color:rgba(0, 0, 0, 0);\n"
"    border: none;\n"
"    border-bottom: 2px solid qlineargradient(spread:pad, x1:0, y1:1, x2:0.970149, y2:0.983, stop:0 rgba(170, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.Password = QtWidgets.QLineEdit(self.frame)
        self.Password.setGeometry(QtCore.QRect(390, 230, 351, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Password.setFont(font)
        self.Password.setStyleSheet("QLineEdit{\n"
"    background-color: rgba(0, 0, 42, 0);\n"
"    font: 14pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    border-bottom: 2px solid qlineargradient(spread:pad, x1:0, y1:1, x2:0.970149, y2:0.983, stop:0 rgba(170, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgba(0, 0, 42, 160);\n"
"}\n"
"\n"
"")
        self.Password.setObjectName("Password")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(500, 70, 101, 61))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255 , 255);")
        self.label_2.setObjectName("label_2")
        self.EnterButton = QtWidgets.QPushButton(self.frame)
        self.EnterButton.setGeometry(QtCore.QRect(700, 233, 41, 41))
        self.EnterButton.setStyleSheet("background-color: rgba(0, 0, 0, 80);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.EnterButton.setObjectName("EnterButton")
        self.User = QtWidgets.QLineEdit(self.frame)
        self.User.setGeometry(QtCore.QRect(390, 160, 335, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.User.setFont(font)
        self.User.setStyleSheet("QLineEdit{\n"
"    background-color: rgba(0, 0, 42, 0);\n"
"    font: 14pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    border-bottom: 2px solid qlineargradient(spread:pad, x1:0, y1:1, x2:0.970149, y2:0.983, stop:0 rgba(170, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgba(0, 0, 42, 160);\n"
"}\n"
"\n"
"")
        self.User.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.User.setCursorPosition(0)
        self.User.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.User.setObjectName("User")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 341, 671))
        self.label_3.setStyleSheet("background-color: rgba(0, 0, 0, 80);\n"
"border-top-left-radius: 50px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(360, 20, 411, 671))
        self.label_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(0, 0, 42, 255), stop:1 rgba(0, 0, 70, 255));\n"
"border-bottom-right-radius: 50px;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.close_button = QtWidgets.QPushButton(self.frame)
        self.close_button.setGeometry(QtCore.QRect(710, 20, 61, 31))
        self.close_button.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(255, 10, 10);\n"
"}\n"
"\n"
"QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(65, 68, 65);\n"
"}")
        self.close_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../2/image/closebutton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_button.setIcon(icon)
        self.close_button.setIconSize(QtCore.QSize(120, 53))
        self.close_button.setObjectName("close_button")
        self.BoxButton = QtWidgets.QPushButton(self.frame)
        self.BoxButton.setGeometry(QtCore.QRect(726, 160, 16, 51))
        self.BoxButton.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(0, 0, 42, 255), stop:1 rgba(0, 0, 70, 255));\n"
"    border-bottom: 2px solid qlineargradient(spread:pad, x1:0, y1:1, x2:0.970149, y2:0.983, stop:0 rgba(170, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.BoxButton.setText("")
        self.BoxButton.setObjectName("BoxButton")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(590, 290, 151, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setUnderline(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton:hover{\n"
"    color: rgb(251, 255, 0);\n"
"}\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border: none;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(-20, 50, 211, 141))
        self.label_6.setStyleSheet("background-image: url(:/newPrefix/278648865_716532036438113_3320425925480882445_n-removebg-preview.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(40, 190, 221, 41))
        self.label_7.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"text-decoration: underline;\n"
"color: rgb(99, 255, 3);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(40, 230, 261, 31))
        self.label_8.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"text-decoration: underline;\n"
"color: rgb(99, 255, 3);")
        self.label_8.setObjectName("label_8")
        self.label.raise_()
        self.label_4.raise_()
        self.Password.raise_()
        self.EnterButton.raise_()
        self.comboBox.raise_()
        self.label_2.raise_()
        self.User.raise_()
        self.close_button.raise_()
        self.BoxButton.raise_()
        self.pushButton.raise_()
        self.label_3.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "rem"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Mai Văn Anh"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Trần Toàn Thắng"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Nguyễn Bá Quốc Tài"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Rem"))
        self.Password.setPlaceholderText(_translate("MainWindow", "Enter your Password"))
        self.label_2.setText(_translate("MainWindow", "LOGIN"))
        self.EnterButton.setText(_translate("MainWindow", "->"))
        self.User.setPlaceholderText(_translate("MainWindow", "Enter your User", "10"))
        self.pushButton.setText(_translate("MainWindow", "Forgot your password"))
        self.label_7.setText(_translate("MainWindow", "Hãy trồng rau"))
        self.label_8.setText(_translate("MainWindow", "Nếu không GS Anh sẽ ăn thịt bạn"))
import image_main_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
